networks:
  default:
    driver: bridge

services:
  explorer:
    container_name: dsv-rpc-explorer
    #define $UID, $GID in .env file the user to run docker and write in data folder
    #user: "1000:1000"
    environment:
      DSVEXP_HOST: 0.0.0.0
      DSVEXP_DORIANCOIND_URI: $DSVEXP_DORIANCOIND_URI
      DSVEXP_ADDRESS_API: $DSVEXP_ADDRESS_API
      DSVEXP_ELECTRUM_SERVERS: $DSVEXP_ELECTRUM_SERVERS
      DSVEXP_SLOW_DEVICE_MODE: false
      #More privacy mode, no external queries
      # DSVEXP_PRIVACY_MODE: true
      # DSVEXP_UI_THEME: dark
    build:
      context: ./
    image: dsv-rpc-explorer:latest
    #restart: "no"
    ports:
      - "3002:3002"
